
export const  RestrauntList = [
    {
      src:"https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/b4817ea5bb972089f419c6f14e5a0bdd",
      named:"Burger-king",
      rating:"4.1",
      time:"35-40min",
      dishes:"Chinese,AsianmTibetan,Desserts"
    },
    {
      src:"https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/2b4f62d606d1b2bfba9ba9e5386fabb7",
      named:"Burger-king",
      rating:"4.1",
      time:"35-40min",
      dishes:"Chinese,AsianmTibetan,Desserts"
    },
    {
      src:"https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/ubypvyevkrogfvj1ygio",
      named:"Burger-king",
      rating:"4.1",
      time:"35-40min",
      dishes:"Chinese,AsianmTibetan,Desserts"
    },
    {
      src:"https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/xxh8c7ggvlhlzlx3oyv4",
      named:"Burger-king",
      rating:"4.1",
      time:"35-40min",
      dishes:"Chinese,AsianmTibetan,Desserts"
    },
    {
      src:"https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/xxh8c7ggvlhlzlx3oyv4",
      named:"Burger-king",
      rating:"4.1",
      time:"35-40min",
      dishes:"Chinese,AsianmTibetan,Desserts" 
    },
    {
      src:"https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/xxh8c7ggvlhlzlx3oyv4",
      named:"Burger-king",
      rating:"4.1",
      time:"35-40min",
      dishes:"Chinese,AsianmTibetan,Desserts"
    }]